In [1]:
# Задание 1
# Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

import numpy as np

a = np.arange(12, 24)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [2]:
# Задание 2
# Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

a1 = a.reshape(1, 12)
a2 = a.reshape(2, 6)
a3 = a.reshape(6, 2)
a4 = a.reshape(3, 4)
a5 = a.reshape(4, 3)


print(a1)
print()
print(a2)
print()
print(a3)
print()
print(a4)
print()
print(a5)

[[12 13 14 15 16 17 18 19 20 21 22 23]]

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [3]:
# Задание 3
# Создать 5 двумерных массивов разной формы из массива a. 
# Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

a1 = a.reshape(12, -1)
a2 = a.reshape(2, -1)
a3 = a.reshape(-1, 2)
a4 = a.reshape(-1, 4)
a5 = a.reshape(-1, 3)


print(a1)
print()
print(a2)
print()
print(a3)
print()
print(a4)
print()
print(a5)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [ ]:
# Задание 4
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Нет.

In [4]:
# Задание 5
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 
# и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

a = np.random.randn(3, 4)
print(a)

[[ 0.73217164  0.39247984  1.50811296 -0.96495504]
 [-1.72238959 -0.22684864  0.80404841 -2.45889848]
 [-1.00254985  0.12721257 -0.02533537  1.91830157]]


In [5]:
b = a.flatten()
print(b)

[ 0.73217164  0.39247984  1.50811296 -0.96495504 -1.72238959 -0.22684864
  0.80404841 -2.45889848 -1.00254985  0.12721257 -0.02533537  1.91830157]


In [6]:
# Задание 6
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [8]:
# Задание 7
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. 
# В чем разница между массивами a и b?

b = np.arange(20, 1, -2)
print(b)

#Разницы между массивами a и b нет.

[20 18 16 14 12 10  8  6  4  2]


In [9]:
# Задание 8
# Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
# чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.vstack((a, b))
print('Массив a', a, sep='\n')
print('Массив b', b, sep='\n')
print('Массив v', v, sep='\n')
v.size

Массив a
[[0. 0.]
 [0. 0.]]
Массив b
[[1. 1.]
 [1. 1.]
 [1. 1.]]
Массив v
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


10

In [10]:
# Задание 9
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
# Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
# Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
# Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
A = a.reshape(4, 3)
print(A)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [12]:
At = np.transpose(A)
print(At)

[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [13]:
B = A.dot(At)
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [14]:
B.size
# Размер матрицы B 4х4.

16

In [15]:
d = np.linalg.det(B)
print(d)
# Вычислить обратную матрицу для матрицы B не получиться.
# Обратную матрицу можно посчитать только для матрицы,определитель которой не равен 0.

0.0
